### ISSUE TITLE
Downloading links

### ISSUE THREAD

**Issue by mariantanase** [thexmanxyz/Logo-Image-Hover-Gantry#2]
Hi Andreas,
I notice that the links for downloading the **Logo-Image-Hover** particle are broken, I mean the links for the plugin versions. Points to the 404 error page.
Can you check please ?
Thanks

**Comment by thexmanxyz** [comment]
Hello @mariantanase,

I fixed the links. The issue must already have been persisted longer as it seems, copy & paste failure. Thanks for pointing out!

/closed
